name: 'stack-fold-action'
description: 'Folds a stack of PRs into themselves'
author: 'Your name or organization here'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  TRUNK_BRANCH:
    description: 'Branch name of your trunk (ie develop/main)'
    required: true
    default: 'main'

# Define your outputs here.
outputs:
  time:
    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
