on:
  pull_request:
    types: [labeled]

jobs:
  fold_me_job:
    if: "contains(github.event.pull_request.labels.*.name, 'fold me')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          milliseconds: 1000

      - name: Print Output
        id: output
        run: echo "${{ steps.test-action.outputs.time }}"
