on:
  pull_request:
    types: [labeled]

permissions:
  contents: write
  pull-requests: write

jobs:
  fold_me_job:
    if: "contains(github.event.pull_request.labels.*.name, 'fold me')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          TRUNK_BRANCH: main
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
